name = "PlusCosmicPack"
author = "itsDinkd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5e1ca6bec3d86454cc34131de795a285480f9c476f8217efbe6db7003bcd9ed"

[versions]
forge = "40.2.7"
minecraft = "1.18.2"
