name = "PlusCosmicPack"
author = "PlusCosmic"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ed0fb323e94473b46e01151ad1b2df52e02999d804a296d9149ef1bcb5ebe3b"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
