name = "PlusCosmicPack"
author = "PlusCosmic"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c663187f273dac3e4c83dba9ef4da02558594abd19b6f159362e248399c22a04"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
